package com.goforcode.grocerygallery.configuration;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import org.springframework.security.crypto.password.PasswordEncoder;

import com.goforcode.grocerygallery.models.Item;
import com.goforcode.grocerygallery.models.ItemReference;
import com.goforcode.grocerygallery.models.User;
import com.goforcode.grocerygallery.repositories.ItemReferenceRepository;
import com.goforcode.grocerygallery.repositories.ItemRepository;
import com.goforcode.grocerygallery.repositories.UserRepository;

public class SeedData {
	
	private UserRepository userRepo;
	private ItemRepository itemRepo;
	private PasswordEncoder encoder;
	private ItemReferenceRepository itemRefRepo;
	
	public SeedData(UserRepository userRepo, ItemRepository itemRepo, PasswordEncoder encoder,
					ItemReferenceRepository itemRefRepo) {
		this.userRepo = userRepo;
		this.itemRepo = itemRepo;
		this.encoder = encoder;
		this.itemRefRepo = itemRefRepo;
	}

	public void create() throws ParseException {
		
//		 
//				
//		User priya = new User("Priya", "Prabhakar", "Priya@gmail.com", encoder.encode("password"), "USER");
//		userRepo.save(priya);
////		System.out.println("Priya's ID is: " + priya.getId());
//		
//		Item brocolli = new Item("Brocolli", "Produce", sdf.parse("10/1/2017"), sdf.parse("10/20/2017"));
//		brocolli.setUser(priya);
//		brocolli.setInFridge(true);
//		brocolli.setLevel(brocolli.calculateLevel());
////		System.out.println("Broccoli level is: " + brocolli.getLevel());
//		itemRepo.save(brocolli);
//		
//		Item milk = new Item("Milk", "", sdf.parse("10/2/2017"), sdf.parse("10/18/2017"));
//		milk.setUser(priya);
//		milk.setInFridge(true);
//		milk.setLevel(milk.calculateLevel());
////		System.out.println("Milk level is: " + milk.getLevel());
//		itemRepo.save(milk);
//		
//		Item eggs = new Item("Eggs");
//		eggs.setUser(priya);
//		eggs.setInGrocery(true);
//		eggs.setLevel(eggs.calculateLevel());
//		eggs.validateCategoryAndDates();
////		System.out.println("Eggs level is: " + eggs.getLevel());
//		eggs.setInFridge(true);
////		System.out.println("EGG CATEGORY: " + eggs.getCategory() + 
////				"EGG EXP DATE: " + eggs.getExpirationDate() 
////				+ "EGG PURCHASE DATE " + eggs.getpurchasedDate());
//		itemRepo.save(eggs);
//		
//		Item chickenFeet = new Item("Chicken Feet", "Eggs/Dairy", sdf.parse("10/4/2017"), sdf.parse("10/22/2017"));
//		chickenFeet.setUser(priya);
//		chickenFeet.setInGrocery(true);
//		chickenFeet.setLevel(chickenFeet.calculateLevel());
////		System.out.println("Chicken feet level is: " + chickenFeet.getLevel());
//		itemRepo.save(chickenFeet);
//		
//		Item lettuce = new Item("Lettuce", "Produce", sdf.parse("10/3/2017"), sdf.parse("10/21/2017"));
//		lettuce.setUser(priya);
//		lettuce.setTrashDate(sdf.parse("10/10/2017"));
//		lettuce.setWasFinished(true);
//		lettuce.setLevel(lettuce.calculateLevel());
////		System.out.println("Lettuce level is: " + lettuce.getLevel());
//		itemRepo.save(lettuce);
//		
//		Item apples = new Item("Apples", "Produce", sdf.parse("10/5/2017"), sdf.parse("10/29/2017"));
//		apples.setUser(priya);
//		apples.setTrashDate(sdf.parse("10/10/2017"));
//		apples.setWasWasted(true);
//		apples.setLevel(apples.calculateLevel());
////		System.out.println("apples level is: " + apples.getLevel());
//		itemRepo.save(apples);
//		
//		Item ketchup = new Item("Ketchup", "Condiments", sdf.parse("10/1/2017"), sdf.parse("12/1/2017"));
//		ketchup.setUser(priya);
//		ketchup.setInFridge(true);
//		ketchup.setLevel(ketchup.calculateLevel());
////		System.out.println("Ketchup level is: " + ketchup.getLevel());
////		System.out.println("Ketchup level is: " + ketchup.calculateLevel());
//		itemRepo.save(ketchup);
//		
//		Item bread = new Item("Bread", "Grains/Nuts", sdf.parse("10/1/2017"), sdf.parse("12/30/2017"));
//		bread.setUser(priya);
//		bread.setInFridge(true);
//		bread.setLevel(bread.calculateLevel());
////		System.out.println("Bread level is: " + bread.getLevel());
////		System.out.println("Bread level is: " + bread.calculateLevel());
//		itemRepo.save(bread);
//		
//		Item lemon = new Item("Lemon", "Produce", sdf.parse("10/09/2017"), sdf.parse("10/12/2017"));
//		lemon.setUser(priya);
//		lemon.setInFridge(true);
//		lemon.setLevel(lemon.calculateLevel());
////		System.out.println("Lemon level is: " + lemon.getLevel());
//		itemRepo.save(lemon);
//		
//		Item onion = new Item("Onions", "Produce", sdf.parse("10/6/2017"), sdf.parse("10/30/2017"));
//		onion.setUser(priya);
//		onion.setTrashDate(sdf.parse("10/10/2017"));
//		onion.setWasWasted(true);
//		onion.setLevel(onion.calculateLevel());
////		System.out.println("Onion level is: " + onion.getLevel());
//		itemRepo.save(onion);
//		
//		Item potatoes = new Item("Potatoes", "Produce", sdf.parse("10/20/2017"), sdf.parse("12/31/2017"));
//		potatoes.setUser(priya);
//		potatoes.setTrashDate(sdf.parse("10/13/2017"));
//		potatoes.setWasWasted(true);
//		potatoes.setLevel(potatoes.calculateLevel());
////		System.out.println("Potato level is: " + potatoes.getLevel());
//		itemRepo.save(potatoes);
//		
////		User tania = new User("Tania@gmail.com", encoder.encode("password"), "USER");
////		userRepo.save(tania);
////		
////		Item tomatoes = new Item("Tomatoes", "Produce", sdf.parse("10/13/2017"), sdf.parse("12/15/2017"));
////		tomatoes.setUser(tania);
////		tomatoes.setInFridge(true);
////		tomatoes.setLevel(tomatoes.calculateLevel());
////		itemRepo.save(tomatoes);
////		
////		Item bread1 = new Item("Bread", "Produce", sdf.parse("10/1/2017"), sdf.parse("10/30/2017"));
////		bread1.setUser(tania);
////		bread1.setInGrocery(true);
////		bread1.setLevel(bread1.calculateLevel());
////		itemRepo.save(bread1);
//		
		
		ItemReference item = new ItemReference("Broccoli", 7);
		itemRefRepo.save(item);
		item = new ItemReference("Carrots", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Cauliflower", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Celery", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Corn", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Cucumbers", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Lettuce / Greens", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Mushrooms", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Onions", 7);
		itemRefRepo.save(item);
		item = new ItemReference("Peppers", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Potatoes", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Spinach", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Squash", 7);
		itemRefRepo.save(item);
		item = new ItemReference("Zucchini", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Tomatoes*", 17);
		itemRefRepo.save(item);
		item = new ItemReference("BBQ sauce", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Gravy", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Honey", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Hot sauce", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Jam / Jelly / Preserves", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Ketchup / Mustard", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Mayonnaise", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Pasta sauce", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Relish", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Salad dressing", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Salsa", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Soy sauce", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Steak sauce", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Syrup", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Worcestershire sauce", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Butter / Margarine", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Cottage cheese", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Half & half", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Milk", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Sour cream", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Whipped cream", 7);
		itemRefRepo.save(item);
		item = new ItemReference("Yogurt", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Bagels / Croissants", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Buns / Rolls", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Cake / Cookies", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Donuts / Pastries", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Fresh bread", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Pie! Pie! Pie!", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Pita bread", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Sliced bread", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Antiperspirant / Deodorant", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Bath soap / Hand soap", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Condoms / Other b.c.", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Cosmetics", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Cotton swabs / Balls", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Facial cleanser", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Facial tissue", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Feminine products", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Floss", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Hair gel / Spray", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Lip balm", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Moisturizing lotion", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Mouthwash", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Razors / Shaving cream", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Shampoo / Conditioner", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Sunblock", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Toilet paper", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Toothpaste", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Vitamins / Supplements", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Air freshener", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Bathroom cleaner", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Bleach / Detergent", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Dish / Dishwasher soap", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Garbage bags", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Glass cleaner", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Mop head / Vacuum bags", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Sponges / Scrubbers", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Apples", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Avocados", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Bananas", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Berries", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Cherries", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Grapefruit", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Grapes", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Kiwis", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Lemons / Limes", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Melon", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Nectarines", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Oranges", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Peaches", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Pears", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Plums", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Bagels", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Chip dip", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Eggs / Fake eggs", 4);
		itemRefRepo.save(item);
		item = new ItemReference("English muffins", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Fruit juice", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Hummus", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Ready-bake breads", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Tofu", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Tortillas", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Breakfasts", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Burritos", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Fish sticks", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Fries / Tater tots", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Ice cream / Sorbet", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Juice concentrate", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Pizza", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Pizza Rolls", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Popsicles", 20);
		itemRefRepo.save(item);
		item = new ItemReference("TV dinners", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Vegetables", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Bouillon cubes", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Cereal", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Coffee / Filters", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Instant potatoes", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Lemon / Lime juice", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Mac & cheese", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Olive oil", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Packaged meals", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Pancake / Waffle mix", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Pasta", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Peanut butter", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Pickles", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Rice", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Tea", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Vegetable oil", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Vinegar", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Applesauce", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Baked beans", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Broth", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Fruit", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Olives", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Tinned meats", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Tuna / Chicken", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Soup / Chili", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Tomatoes", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Veggies", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Basil", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Black pepper", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Cilantro", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Cinnamon", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Garlic", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Ginger", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Mint", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Oregano", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Paprika", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Parsley", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Red pepper", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Salt", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Vanilla extract", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Bleu cheese", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Cheddar", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Cottage cheese", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Cream cheese", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Feta", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Goat cheese", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Mozzarella", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Parmesan", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Provolone", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Ricotta", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Sandwich slices", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Swiss", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Bacon / Sausage", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Beef", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Chicken", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Ground beef / Turkey", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Ham / Pork", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Hot dogs", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Lunchmeat", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Turkey", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Catfish", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Crab", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Lobster", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Mussels", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Oysters", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Salmon", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Shrimp", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Tilapia", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Tuna", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Beer", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Club soda / Tonic", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Champagne", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Gin", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Juice", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Mixers", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Red wine / White wine", 6);
		itemRefRepo.save(item);
		item = new ItemReference("Rum", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Saké", 2);
		itemRefRepo.save(item);
		item = new ItemReference("Soda pop", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Sports drink", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Whiskey", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Vodka", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Baking powder / Soda", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Bread crumbs", 13);
		itemRefRepo.save(item);
		item = new ItemReference("Cake / Brownie mix", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Cake icing / Decorations", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Chocolate chips / Cocoa", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Flour", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Shortening", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Sugar", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Sugar substitute", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Yeast", 14);
		itemRefRepo.save(item);
		item = new ItemReference("Candy / Gum", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Cookies", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Crackers", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Dried fruit", 15);
		itemRefRepo.save(item);
		item = new ItemReference("Granola bars / Mix", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Nuts / Seeds", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Oatmeal", 9);
		itemRefRepo.save(item);
		item = new ItemReference("Popcorn", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Potato / Corn chips", 4);
		itemRefRepo.save(item);
		item = new ItemReference("Pretzels", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Burger night", 12);
		itemRefRepo.save(item);
		item = new ItemReference("Chili night", 5);
		itemRefRepo.save(item);
		item = new ItemReference("Pizza night", 19);
		itemRefRepo.save(item);
		item = new ItemReference("Spaghetti night", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Taco night", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Take-out deli food", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Baby food", 17);
		itemRefRepo.save(item);
		item = new ItemReference("Diapers", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Formula", 3);
		itemRefRepo.save(item);
		item = new ItemReference("Lotion", 18);
		itemRefRepo.save(item);
		item = new ItemReference("Baby wash", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Wipes", 10);
		itemRefRepo.save(item);
		item = new ItemReference("Cat food / Treats", 20);
		itemRefRepo.save(item);
		item = new ItemReference("Cat litter", 16);
		itemRefRepo.save(item);
		item = new ItemReference("Dog food / Treats", 8);
		itemRefRepo.save(item);
		item = new ItemReference("Flea treatment", 11);
		itemRefRepo.save(item);
		item = new ItemReference("Pet shampoo", 11);
		itemRefRepo.save(item);
		
		User user = new User("Priya", "Pree", "priya@gmail.com", encoder.encode("password"), "USER");
		userRepo.save(user);
		
		SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");

		
		Item fridgeItem = new Item("Melon", sdf.parse("10/17/2017"), sdf.parse("10/19/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Nectarines", sdf.parse("10/19/2017"), sdf.parse("11/01/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Oranges", sdf.parse("10/19/2017"), sdf.parse("11/01/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Peaches", sdf.parse("10/22/2017"), sdf.parse("10/23/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Pears", sdf.parse("10/19/2017"), sdf.parse("11/01/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Plums", sdf.parse("10/18/2017"), sdf.parse("10/23/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);
		fridgeItem = new Item("Bagels", sdf.parse("10/17/2017"), sdf.parse("10/31/2017"));
		fridgeItem.setUser(user); fridgeItem.setInFridge(true);
		itemRepo.save(fridgeItem);	
	
		
	}
	
}
